### ISSUE TITLE
mvn test failing on windows 7 due to UNI Code (?)

### ISSUE THREAD

**Issue by pclausen** [almondtools/tante-emmas#5]
It looks to me that the diff is caused simply because of UNI Code character (c). 

Any suggestions how to avoid this or maybe for portability replace the UniCode character with (c) ?

Diff files:

```
E:\code\gitrepos\tante-emmas>diff E:\code\gitrepos\tante-emmas\src\test\java\net\amygdalum\tanteemmas\ApprovalsTest.check_order.received.html E:\code\gitrepos\tante-emmas\src\test\java\net\amygdalum\tanteemmas\ApprovalsTest.check_order.approved.html
239c239
<                                               ® 2014 eNno Multi-purpose theme | <a target="_blank" href="http://bootstraptaste.com">Bootstraptaste</a>
---
>                                               ┬® 2014 eNno Multi-purpose theme | <a target="_blank" href="http://bootstraptaste.com">Bootstraptaste</a>

```

I am using Windows 7 SP1
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
jdk1.8.0_112

**Comment by almondtools** [comment]
You probably work on the [retest fork of tante emmas](https://github.com/retest/tante-emmas), aren't you?
